from pymongo import MongoClient
from pymongo.errors import AutoReconnect
import datetime
import time
import sys

client = MongoClient("mongodb://admin:secret@192.168.43.201:27017,192.168.43.202:27017,192.168.43.203:27017/admin?serverSelectionTimeout=5&socketTimeoutMs=20&replicaSet=rs0")

db = client['test']

while True:
    try:
        post = {"author": "Test", "text": "This is a test!", "date": datetime.datetime.utcnow()}
        db['test_collection'].insert_one(post)
        post = None
    except AutoReconnect as auto:
        print("An error occured: {0}".format(auto))
        print("Sleeping for 10 seconds before retry...")
        time.sleep(10)
        try:
            db['test_collection'].insert_one(post)
            print("Recovered a post after member failure. Continuing in 10 seconds...")
            time.sleep(10)
        except Exception as excep:
            print("Lost a document after retry. {0}".format(str(excep)))
            print("Contining in 10 seconds...")
            time.sleep(10)
    finally:
        client.close()
